### ISSUE TITLE
cv2.error

### ISSUE THREAD

**Issue by jafarlie** [ankurg22/object-tracking#1]
Running the program on macOS High Sierra gives following error:
File "write_in_air.py", line 18, in <module>
    blur_frame = cv2.GaussianBlur(frame, (7, 7), 0)
cv2.error: /Users/travis/build/skvark/opencv-python/opencv/modules/core/src/matrix.cpp:991: error: (-215) dims <= 2 && step[0] > 0 in function locateROI

**Comment by ankurg22** [comment]
@jafarlie Change the webcam number to 0. 0 means primary webcam and 1 is secondary.
```cv2.VideoCapture(0)```
Let me know if this solves the error.
